spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      show_sql: true
      format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver

